### ISSUE TITLE
build basic frontend login screen (200 points)

### ISSUE THREAD

**Issue by chan4est** [ucsb-cs56-webapps/ucsb-cs56-gauchogains#5]
**200 points**

**Comment by benye11** [comment]
Got em.

**Comment by chan4est** [comment]
Completed in both these PRs

https://github.com/ucsb-cs56-webapps/ucsb-cs56-gauchogains/pull/13
https://github.com/ucsb-cs56-webapps/ucsb-cs56-gauchogains/pull/14
